// <auto-generated />
using System;
using Biblioteka.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteka.Infrastructure.Migrations
{
    [DbContext(typeof(BibliotekaContext))]
    partial class BibliotekaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Biblioteka.Domain.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biografija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AutorId");

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("Biblioteka.Domain.Bibliotekar", b =>
                {
                    b.Property<string>("Jmbg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Jmbg");

                    b.ToTable("Bibliotekari");
                });

            modelBuilder.Entity("Biblioteka.Domain.Clan", b =>
                {
                    b.Property<string>("Jmbg")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GradId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Jmbg");

                    b.HasIndex("GradId");

                    b.ToTable("Clanovi");
                });

            modelBuilder.Entity("Biblioteka.Domain.Grad", b =>
                {
                    b.Property<int>("GradId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GradId");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("Biblioteka.Domain.Izdavanje", b =>
                {
                    b.Property<int>("IzdavanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BibliotekarJmbg")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClanJmbg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumVracanja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IzdavanjeId");

                    b.HasIndex("BibliotekarJmbg");

                    b.HasIndex("ClanJmbg");

                    b.ToTable("Izdavanja");
                });

            modelBuilder.Entity("Biblioteka.Domain.Knjiga", b =>
                {
                    b.Property<int>("KnjigaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojStrana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GodinaIzdanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Zanr")
                        .HasColumnType("INTEGER");

                    b.HasKey("KnjigaId");

                    b.ToTable("Knjige");
                });

            modelBuilder.Entity("Biblioteka.Domain.Pisanje", b =>
                {
                    b.Property<int>("KnjigaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KnjigaId", "AutorId");

                    b.HasIndex("AutorId");

                    b.ToTable("Pisanje");
                });

            modelBuilder.Entity("Biblioteka.Domain.StavkaIzdavanja", b =>
                {
                    b.Property<int>("IzdavanjeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnjigaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IzdavanjeId", "KnjigaId");

                    b.HasIndex("KnjigaId");

                    b.ToTable("StavkaIzdavanja");
                });

            modelBuilder.Entity("Biblioteka.Domain.Clan", b =>
                {
                    b.HasOne("Biblioteka.Domain.Grad", "Grad")
                        .WithMany("Clanovi")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("Biblioteka.Domain.Izdavanje", b =>
                {
                    b.HasOne("Biblioteka.Domain.Bibliotekar", "Bibliotekar")
                        .WithMany("Izdavanja")
                        .HasForeignKey("BibliotekarJmbg");

                    b.HasOne("Biblioteka.Domain.Clan", "Clan")
                        .WithMany("Izdavanja")
                        .HasForeignKey("ClanJmbg")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bibliotekar");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("Biblioteka.Domain.Pisanje", b =>
                {
                    b.HasOne("Biblioteka.Domain.Autor", "Autor")
                        .WithMany("Pisanja")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteka.Domain.Knjiga", "Knjiga")
                        .WithMany("Pisanja")
                        .HasForeignKey("KnjigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Knjiga");
                });

            modelBuilder.Entity("Biblioteka.Domain.StavkaIzdavanja", b =>
                {
                    b.HasOne("Biblioteka.Domain.Izdavanje", "Izdavanje")
                        .WithMany("StavkeIzdavanja")
                        .HasForeignKey("IzdavanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteka.Domain.Knjiga", "Knjiga")
                        .WithMany("StavkeIzdavanja")
                        .HasForeignKey("KnjigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izdavanje");

                    b.Navigation("Knjiga");
                });

            modelBuilder.Entity("Biblioteka.Domain.Autor", b =>
                {
                    b.Navigation("Pisanja");
                });

            modelBuilder.Entity("Biblioteka.Domain.Bibliotekar", b =>
                {
                    b.Navigation("Izdavanja");
                });

            modelBuilder.Entity("Biblioteka.Domain.Clan", b =>
                {
                    b.Navigation("Izdavanja");
                });

            modelBuilder.Entity("Biblioteka.Domain.Grad", b =>
                {
                    b.Navigation("Clanovi");
                });

            modelBuilder.Entity("Biblioteka.Domain.Izdavanje", b =>
                {
                    b.Navigation("StavkeIzdavanja");
                });

            modelBuilder.Entity("Biblioteka.Domain.Knjiga", b =>
                {
                    b.Navigation("Pisanja");

                    b.Navigation("StavkeIzdavanja");
                });
#pragma warning restore 612, 618
        }
    }
}
